version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /volume2/docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - appnetwork

  tcplistener:
    image: yourusername/tcplistener:1.0
    container_name: tcplistener
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=Username=${DB_USER};Password=${DB_PASSWORD};Host=192.168.0.175;Port=5433;Database=${DB_NAME};Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;Connection Lifetime=0;
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge